version: '3.8'
services:
  weather-app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - WEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - .:/app              # Mount source code
      - /app/node_modules   # Keep container's node_modules