const express = require('express');
const weatherController = require('../controllers/weatherController');

const router = express.Router();

// Generated by Copilot
router.get('/weather/:city/:units', weatherController.getCurrentWeather);
router.get('/forecast/:city/:units', weatherController.getForecast);

module.exports = router;