name: Deploy to Render

on:
  push:
    branches:
      - enhanced-main
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dockerimage
        run: docker build .
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        if: ${{ hashFiles('**/test/**', '**/*.test.js') != '' }}
        run: |
          if npm run | grep -q "test"; then
            npm test -- --passWithNoTests
          else
            echo "No test script found in package.json. Skipping tests."
          fi

      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}